### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void com.kbeanie.imagechooser.api.ImageChooserManager.submit(int, android.content.Intent)' on a null object reference

### ISSUE THREAD

**Issue by WOSHICAIXIANFENG** [coomar2841/image-chooser-library#122]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.kbeanie.imagechooser.api.ImageChooserManager.submit(int, android.content.Intent)' on a null object reference
            at com.dtc.module.form.CollectionPhotoHandling.submitImageData(CollectionPhotoHandling.java:81)
            at com.dtc.module.main.ListCollectionInformationFragment.onActivityResult(ListCollectionInformationFragment.java:241)
            at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:165)
            at android.app.Activity.dispatchActivityResult(Activity.java:6192)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)

**Comment by WOSHICAIXIANFENG** [comment]
CollectionPhotoHandling.java:81

// Callback when image data response, call after 'onActivityResult'
public void submitImageData(int requestCode, Intent data) {
      mImageChooser.submit(requestCode, data);
}

**Comment by AlexPGA** [comment]
i have the same error. How do you solve it? thanks for your reply

**Comment by coomar2841** [comment]
Is `mImagechooser` null? If yes, you will have to reinitialize it.

**Comment by AlexPGA** [comment]
coomar2841 thanks for this and all replys. I solve my problems
