### ISSUE TITLE
onError in Fragment called too soon causing NPE

### ISSUE THREAD

**Issue by fliespl** [coomar2841/image-chooser-library#138]
On some devices returning to fragment with image chooser could lead to NPE (either error or success).

This is because onError is called before activity is available to fragment (getActivity() is still null).

Fatal Exception: java.lang.NullPointerException
       at xxx.com.SomeFragment.onError(SomeFragment.java:252)
       at com.kbeanie.imagechooser.api.ImageChooserManager.onError(ImageChooserManager.java:309)
       at com.kbeanie.imagechooser.threads.ImageProcessorThread.run(ImageProcessorThread.java:57)

**Comment by coomar2841** [comment]
In these circumstances, you should be re-initializing the chooser managers. Can you try the sample app and see if they work for your. There's a fragment option which shows how to handle in a fragment.
