### ISSUE TITLE
Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by virengujariya** [coomar2841/image-chooser-library#168]
```Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at com.kbeanie.imagechooser.api.ChosenMedia.getWidth(ChosenMedia.java:38)
       at com.kbeanie.imagechooser.api.ChosenImage.getMediaWidth(ChosenImage.java:58)```

Mostly on samsung devices running OS 6

**Comment by arpit999bicubic** [comment]
see http://stackoverflow.com/questions/33343191/nullpointerexception-attempt-to-invoke-virtual-method-int-android-graphics-bit

**Comment by hoyun293** [comment]
mine is also S6..
and i tried to use ExifInterface   to rotate my Images
but this one also goes to fail -3-
