### ISSUE TITLE
 java.lang.NullPointerException at java.io.File.fixSlashes when select photo from gallery 

### ISSUE THREAD

**Issue by amineghabi** [coomar2841/image-chooser-library#170]

**Comment by ramesh586** [comment]
Can we have a error log. It might help us to solve your problem

**Comment by donnadanley247** [comment]
Here's my error reported by some users,


```
java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done(AsyncTask.java:309)
  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: 
  at java.io.File.fixSlashes(File.java:183)
  at java.io.File.<init>(File.java:130)
  at com.bumptech.glide.DrawableTypeRequest.buildProvider(DrawableTypeRequest.java:0)
  at com.bumptech.glide.DrawableTypeRequest.doInBackground(DrawableTypeRequest.java:0)
  at android.os.AsyncTask$2.call(AsyncTask.java:295)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)

```

**Comment by ramesh586** [comment]
@donnadanley247 
Can you provide the code snippet how you are creating file .

**Comment by donnadanley247** [comment]
I don't know even where is the error coming. Because i am receiving this
stack trace from play store crashes and firebase crashes with just provided
details. App in my testing devices working fine so i can not decide where
the problem is.

**Comment by coomar2841** [comment]
Can you tell which device and OS?
