### ISSUE TITLE
Bug: resource leak found in strict mode

### ISSUE THREAD

**Issue by umesh0492** [coomar2841/image-chooser-library#198]
Strict mode configuration 
StrictMode.setThreadPolicy (new StrictMode.ThreadPolicy.Builder ()
                    .detectDiskReads ()
                    .detectDiskWrites ()
                    .detectNetwork ()
                    .detectAll ()// or .detectAll() for all detectable problems
                    .penaltyLog ()
                    .build ());
            StrictMode.setVmPolicy (new StrictMode.VmPolicy.Builder ()
                    .detectLeakedSqlLiteObjects ()
                    .detectLeakedClosableObjects ()
                    .penaltyLog ()
                    .penaltyDeath ()
                    .build ());

E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                      java.lang.Throwable: Explicit termination method 'close' not called
                                                                          at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                          at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                                                          at java.io.FileInputStream.<init>(FileInputStream.java:103)
                                                                          at android.media.ExifInterface.loadAttributes(ExifInterface.java:1342)
                                                                          at android.media.ExifInterface.<init>(ExifInterface.java:1061)
                                                                          at com.kbeanie.multipicker.core.threads.FileProcessorThread.getHeightOfImage(FileProcessorThread.java:779)
                                                                          at com.kbeanie.multipicker.core.threads.ImageProcessorThread.generateMetadata(ImageProcessorThread.java:96)
                                                                          at com.kbeanie.multipicker.core.threads.ImageProcessorThread.postProcessImage(ImageProcessorThread.java:81)
                                                                          at com.kbeanie.multipicker.core.threads.ImageProcessorThread.postProcessImages(ImageProcessorThread.java:65)
                                                                          at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:42)

**Comment by jzeferino** [comment]
Got the same issue.
Any way to solve this?
