### ISSUE TITLE
Samsung Galaxy S4 ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by ozix** [coomar2841/image-chooser-library#59]
I/ImageChooserManager(27319): File: content://media/external/images/media/53529
D/AbsListView(27319): onVisibilityChanged() is called, visibility : 0
I/MediaProcessorThread(27319): Directory size: 8529038
I/MediaProcessorThread(27319): Deleted 0 files
I/ImageProcessorThread(27319): Processing Image File: content://media/external/images/media/53529
I/MediaProcessorThread(27319): Image Uri: content://media/external/images/media/53529
D/AbsListView(27319): unregisterIRListener() is called 
V/GAV4    (27319): Thread[GAThread,5,main]: putHit called
V/GAV4    (27319): Thread[GAThread,5,main]: Sending hit to service   PATH: https:  PARAMS: v=1,  ul=pl-pl,  t=screenview,  ht=1424974054327,  sr=1080x1920,  a=110745433,  an=,  tid=UA-57668548-2,  aid=com.,  cid=5ed470cb-5cb2-4d68-9428-cece44d6f0f3,  av=0.84p-prod-develop,  _u=.r3r398,  cd=com..ui.HomeActivity_,  
D/AbsListView(27319): unregisterIRListener() is called 
I/MediaProcessorThread(27319): Compressing ... THUMBNAIL
I/MediaProcessorThread(27319): Before: 0x0
I/MediaProcessorThread(27319): Scale: 0
I/MediaProcessorThread(27319): Rotate: 0
I/MediaProcessorThread(27319): After: 1050x1152
I/MediaProcessorThread(27319): Compressing ... THUMBNAIL SMALL
I/MediaProcessorThread(27319): Before: 0x0
I/MediaProcessorThread(27319): Scale: 0
I/MediaProcessorThread(27319): Rotate: 0
I/MediaProcessorThread(27319): After: 525x576
D/AbsListView(27319): Get MotionRecognitionManager
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): onDetachedFromWindow
D/AbsListView(27319): unregisterIRListener() is called 
E/ViewRootImpl(27319): sendUserActionEvent() mView == null
W/IInputConnectionWrapper(27319): showStatusIcon on inactive InputConnection
D/AbsListView(27319): onVisibilityChanged() is called, visibility : 4
D/AbsListView(27319): unregisterIRListener() is called 
I/ImageChooserManager(27319): File: content://media/external/images/media/54786
D/AbsListView(27319): onVisibilityChanged() is called, visibility : 0
D/AbsListView(27319): unregisterIRListener() is called 
I/MediaProcessorThread(27319): Directory size: 10379373
V/GAV4    (27319): Thread[GAThread,5,main]: Loaded clientId
I/MediaProcessorThread(27319): Deleted 0 files
I/ImageProcessorThread(27319): Processing Image File: content://media/external/images/media/54786
I/MediaProcessorThread(27319): Image Uri: content://media/external/images/media/54786
V/GAV4    (27319): Thread[GAThread,5,main]: putHit called
I/MediaProcessorThread(27319): Compressing ... THUMBNAIL
E/JHEAD   (27319): can't open '/storage/emulated/0/myfolder/20150214_151157_fact_2.jpg'
I/MediaProcessorThread(27319): Before: 0x0
I/MediaProcessorThread(27319): Scale: 0
I/MediaProcessorThread(27319): Rotate: 0
E/BitmapFactory(27319): Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/myfolder/20150214_151157_fact_2.jpg: open failed: ENOENT (No such file or directory)
W/System.err(27319): java.lang.NullPointerException
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.MediaProcessorThread.compressAndSaveImage(MediaProcessorThread.java:183)
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.MediaProcessorThread.getThumnailPath(MediaProcessorThread.java:116)
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.MediaProcessorThread.createThumbnails(MediaProcessorThread.java:107)
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.ImageProcessorThread.process(ImageProcessorThread.java:108)
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.ImageProcessorThread.processImage(ImageProcessorThread.java:100)
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.ImageProcessorThread.run(ImageProcessorThread.java:57)
W/System.err(27319): java.lang.Exception: Corrupt or deleted file???
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.MediaProcessorThread.compressAndSaveImage(MediaProcessorThread.java:205)
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.MediaProcessorThread.getThumnailPath(MediaProcessorThread.java:116)
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.MediaProcessorThread.createThumbnails(MediaProcessorThread.java:107)
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.ImageProcessorThread.process(ImageProcessorThread.java:108)
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.ImageProcessorThread.processImage(ImageProcessorThread.java:100)
W/System.err(27319): 	at com.kbeanie.imagechooser.threads.ImageProcessorThread.run(ImageProcessorThread.java:57)
V/GAV4    (27319): Thread[GAThread,5,main]: Loaded clientId
D/AbsListView(27319): unregisterIRListener() is called 
V/GAV4    (27319): Thread[GAThread,5,main]: putHit called
V/GAV4    (27319): Thread[GAThread,5,main]: Sending hit to service   PATH: https:  PARAMS: v=1,  ul=pl-pl,  t=screenview,  ht=1424974065012,  sr=1080x1920,  a=110745436,  an=com,  tid=UA-57668548-2,  aid=com.com,  cid=5ed470cb-5cb2-4d68-9428-cece44d6f0f3,  av=0.84p-prod-develop,  _u=.K-AL,  cd=UploadFragment,  
D/AbsListView(27319): Get MotionRecognitionManager
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): onDetachedFromWindow
D/AbsListView(27319): unregisterIRListener() is called 
E/ViewRootImpl(27319): sendUserActionEvent() mView == null
D/AbsListView(27319): unregisterIRListener() is called 
W/IInputConnectionWrapper(27319): showStatusIcon on inactive InputConnection
D/AbsListView(27319): onVisibilityChanged() is called, visibility : 4
D/AbsListView(27319): unregisterIRListener() is called 
D/AbsListView(27319): onDetachedFromWindow
D/AbsListView(27319): unregisterIRListener() is called 
W/ApplicationPackageManager(27319): getCSCPackageItemText()
I/PersonaManager(27319): getPersonaService() name persona_policy

**Comment by ozix** [comment]
It's from version: 1.4.02

**Comment by ruckus** [comment]
I'm seeing this same error with `1.4.3`
