### ISSUE TITLE
Permission Denial: opening provider com.android.gallery3d.provider.GalleryProvider

### ISSUE THREAD

**Issue by kurganec** [coomar2841/image-chooser-library#8]
![2013-08-22 12 10 32](https://f.cloud.github.com/assets/331773/1007222/553a2252-0b02-11e3-90ea-0af3f8f63bbf.png)

Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.gallery3d.provider.GalleryProvider from ProcessRecord{411c6770 20120:com.beanie.imagechooserapp/u0a10161} (pid=20120, uid=10161) requires com.google.android.gallery3d.permission.GALLERY_PROVIDER or com.google.android.gallery3d.permission.GALLERY_PROVIDER
        at android.os.Parcel.readException(Parcel.java:1425)
        at android.os.Parcel.readException(Parcel.java:1379)
        at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2545)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:4648)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2054)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1101)
        at android.content.ContentResolver.query(ContentResolver.java:356)
        at android.content.ContentResolver.query(ContentResolver.java:315)
        at com.beanie.imagechooser.api.BChooser.getAbsoluteImagePathFromUri(BChooser.java:112)
        at com.beanie.imagechooser.api.ImageChooserManager.processImageUri(ImageChooserManager.java:216)
        at com.beanie.imagechooser.api.ImageChooserManager.processImageFromGallery(ImageChooserManager.java:252)
        at com.beanie.imagechooser.api.ImageChooserManager.submit(ImageChooserManager.java:198)
        at com.beanie.imagechooserapp.ImageChooserActivity.onActivityResult(ImageChooserActivity.java:120)
        at android.app.Activity.dispatchActivityResult(Activity.java:5293)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3443)
        ... 11 more

**Comment by coomar2841** [comment]
This should be fixed now. Please check and re-open if it's still an issue.
