### ISSUE TITLE
Take picture is returning back to the app

### ISSUE THREAD

**Issue by sudeep-sr** [coomar2841/image-chooser-library#91]
Open the camera and take picture after that the control is not returning back to the caller . 

Device : Moto G2 OS version: Lolipop 5.1

**Comment by coomar2841** [comment]
Looks like an issue on Lollipop. Checking this. Although this doesn't happen on all devices.

**Comment by coomar2841** [comment]
Does the sample app behave the same way?

**Comment by gogui63** [comment]
I have the same issue, my log : 

 E/StrictMode﹕ file:// Uri exposed through ClipData.Item.getUri()
    java.lang.Throwable: file:// Uri exposed through ClipData.Item.getUri()
            at android.os.StrictMode.onFileUriExposed(StrictMode.java:1603)
            at android.net.Uri.checkFileUriExposed(Uri.java:2342)
            at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
            at android.content.Intent.prepareToLeaveProcess(Intent.java:8581)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1509)
            at android.app.Activity.startActivityForResult(Activity.java:4026)
            at android.app.Activity.startActivityForResult(Activity.java:3973)
            at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:835)
            at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:908)
            at com.kbeanie.imagechooser.api.BChooser.startActivity(BChooser.java:114)
            at com.kbeanie.imagechooser.api.ImageChooserManager.takePicture(ImageChooserManager.java:203)
            at com.kbeanie.imagechooser.api.ImageChooserManager.choose(ImageChooserManager.java:168)
            at my.app.fragments.AbstractFragmentTakePicture.takePicture(AbstractFragmentTakePicture.java:76)
            at my.app.fragments.FragmentMesInformations.onClick(FragmentMesInformations.java:245)
            at android.view.View.performClick(View.java:5254)
            at android.view.View$PerformClick.run(View.java:21173)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6837)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

Work on devices < Lolipop

**Comment by coomar2841** [comment]
Well, I guess you haven't implemented the onSaveInstance to save things when the activity is destroyed. Closing this for now. Please open a new bug if it's still an issue.
